### ISSUE TITLE
Current Status

### ISSUE THREAD

**Issue by andrewkroh** [elastic/winlogbeat#1]
- Current status:
  - ~~Need to decide if this will be a standalone Beat or will be included as part of Filebeat.~~ (it will be standalone)
  - ~~Code is mostly untested~~ and has not been reviewed. (it now has tests, #6, #8)
  - Uses Event Logging API to retrieve events.
  - ~~Always reads from beginning of event log. (It does not persist state so it cannot resume reading.)~~ #13 
- What needs done in current code:
  - ~~Persist last published `recordNumber` for each event log so that eventbeat can resume from last known position.~~ #13
  - Resolve `eventCategory` strings in log records. (API returns an int that must be looked up to get the string).
  - Implement _ignore_older_ filtering (i.e. only send events generated within last 12h).
  - Implement _severity_ filtering (i.e. only send records with `Error` type).
  - Add ability to configure UNC path for reading from remote event logs.
  - Add ability to read from Windows Event Log API (preferred API to get event log data in Windows Vista, Windows Server 2008, and newer).
  - Tests
  - Peer review

- Features being considered:
  - Read registry to automatically detect all event logs. The user would not need to configure which event logs to read. 
  - Read from raw .evt or .evtx files in case you want to index events that were exported or backed up. Implementation hints: [stackoverflow.com](https://stackoverflow.com/questions/7117983/reading-evt-evtx-files-directly)

**Comment by stephanbuys** [comment]
@andrewkroh, sounds good - I think there might be something to keeping it separate. @lmello mentioned that there's already been scaling issues? It looks like you're using the FFI to read the logs, is it related to that?

**Comment by kimchy** [comment]
awesome stuff @andrewkroh!, two high level notes: Seems to me like this should be its own beat compared to being folded into Filebeat. And, naming wise, Eventbeat is generic, I think we will need to add windows or something like that there...

**Comment by ggupta** [comment]
Agree with Shay on naming. We will also likely want to grab other kinds of windows data in the future (registry info, perfmon, etc) in the same Beat. One suggestion is "Winbeat"

**Comment by tbragin** [comment]
I'd probably prefer "winlogbeat", since "wineventlogbeat" is too long :)

**Comment by elvarb** [comment]
I agree with @ggupta , Winbeat would be best, expecially if the same beat will be used in the future for more Windows specific data gathering since it is so different from Linux

**Comment by kimchy** [comment]
I think different type of "Windows" data require different semantics. Does a checkpoint applies when fetching perf mon data compared to event log?

agreed 100% that there are other Windows specific data sources, but then I suspect we will either fold it to another type of beat (like cpu in topbeat) or create another dedicated beat.

**Comment by bahaaldine** [comment]
what about "winbeat" ?

**Comment by tbragin** [comment]
@bahaaldine "winbeat" is what we had before, but felt it was not specific enough - in the future we may have other windows-specific beats.

**Comment by andrewkroh** [comment]
Migrated to elastic/beats#465.
