### ISSUE TITLE
Allow the use of wildcards for Channels

### ISSUE THREAD

**Issue by widhalmt** [elastic/winlogbeat#21]
Hi,

If I want to watch all or almost all log channels on a Windows server the config file becomes quite bulky and defining all the channels is not a fun thing to do.

Could you add the option to add channels via wildcard or an option to add all channels and just blacklist the ones you don't want?

If this is already possible, could you update the documentation to show this?

Cheers,
Thomas

**Comment by andrewkroh** [comment]
All issues for Winlogbeat are tracked [elastic/beats](https://github.com/elastic/beats). This repo is no longer being used. Please open the issue there.
