### ISSUE TITLE
Windows based testing

### ISSUE THREAD

**Issue by stephanbuys** [elastic/winlogbeat#3]
Hi, after reviewing initial Eventbeat outputs (I'm writing straight to file), I can see there are several issues with parsing etc. I'm thinking of writing a simple powershell based test that:

1) creates a `eventbeat` eventlog
2) injects some events (perhaps with a variety of string types, eventtypes, etc)
3) fire up `eventbeat` to parse the logs and direct the output to file
4) Delete the `eventbeat` eventlog
5) Check the content of the file is as expected

Does this sound like a worthwhile exercise?

**Comment by andrewkroh** [comment]
This is definitely a worthwhile exercise! This is the first type of test I was thinking the project should have.

All of the Beats have been using [a python based test framework](https://github.com/elastic/topbeat/tree/master/tests/system) and it has worked out very well. It seems like invoking powershell from python to write/delete the events wouldn't be too difficult.
